# my-helm-app/values.yaml
replicaCount: 2
image:
  repository: nginx
  tag: 1.14.2
  pullPolicy: IfNotPresent
service:
  type: NodePort # Change this line to NodePort
  port: 80
  nodePort: 32000 # Add this line to specify a NodePort
